config/routes.rb
Rails.application.routes.draw do
#  get 'studios/index'
#  get 'studios/show'

  root to: 'toppages#index'

  #トップ・検索ページ
  get 'toppages/index'
  
  #一覧表示ページ
  get 'studios', to: 'studios#index'
  #詳細表示ページ
  get 'studios/:id', to: 'studios#show' , as: 'studio'

  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
  has_many :studios
  
  def self.ranking_method
    ranking = {}
    
    for i in 1..Area.count
      ranking[Area.find(i).name] = Area.find(i).studios.length
    end
    
    return Hash[ ranking.sort_by{ |_, v| -v } ]
    
  end
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  has_many :studio_equipments
  has_many :studios, through: :studio_equipments

  validates :name, presence: true
end

app/models/studio.rb
class Studio < ApplicationRecord
  belongs_to :area
  has_many :studio_photos,dependent: :destroy

  has_many :studio_equipments
  has_many :equipments, through: :studio_equipments
  
  validates :name, presence: true, length: { maximum: 100 }
  validates :area_id, presence: true
  validates :station, presence: true, length: { maximum: 50 }
  validates :address, presence: true, length: { maximum: 200 }
  validates :business_hours, presence: true, length: { maximum: 100 }
  validates :day_off, presence: true, length: { maximum: 50 }
  validates :charge_weekday, presence: true
  validates :charge_holiday, presence: true
  validates :room, presence: true
  validates :url, presence: true, length: { maximum: 200 }
  validates :tel, presence: true, length: { maximum: 50 }
end

app/models/studio_equipment.rb
class StudioEquipment < ApplicationRecord
  belongs_to :studio
  belongs_to :equipment
end

app/models/studio_photo.rb
class StudioPhoto < ApplicationRecord
  belongs_to :studio
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/studios_controller.rb
class StudiosController < ApplicationController
require 'net/http'
require 'json'

BASE_URL_YOLP_GEOCODER = "http://geo.search.olp.yahooapis.jp/OpenLocalPlatform/V1/geoCoder"
APP_ID_YAHOO = "dj00aiZpPVZzVkJ2djcwWnZ4TCZzPWNvbnN1bWVyc2VjcmV0Jng9Yjc-"

  # 住所から緯度経度出力
  def geocode_yolp(address)
    address = URI.encode(address)
    hash = Hash.new
    # 出力形式にJSONを指定する
    reqUrl = "#{BASE_URL_YOLP_GEOCODER}?appid=#{APP_ID_YAHOO}&query=#{address}&output=json"
    response = Net::HTTP.get_response(URI.parse(reqUrl))
    # レスポンスコードのチェック
    case response
    # 200 OK
    when Net::HTTPSuccess then
      data = JSON.parse(response.body)
      # YOLPでの座標情報は緯度経度に分かれていない（カンマ区切りの）ため分解する
      coordinates = data['Feature'][0]['Geometry']['Coordinates'].split(/,\s?/)
      hash['lat'] = coordinates[1].to_f # 緯度
      hash['lng'] = coordinates[0].to_f # 経度
    # それ以外
    else
      hash['lat'] = 0.00
      hash['lng'] = 0.00
    end
    return hash
  end
  
  def index
    # 指定されたエリアで絞る
    if params[:area_id].present?
      @sortby = params[:sortby]
      @area_id = params[:area_id]
      @area = Area.find(@area_id) #該当エリア
      @hit_count = Studio.where(area_id:@area_id).count #ヒット件数
      @studios = @area.studios.order(params[:sort]) #ヒットしたスタジオ達
    else
      puts "This Area has no studios!!"
    end
  end

  def show
    @studio_photo_urls = []
    @studio = Studio.find(params[:id])
    @place = geocode_yolp(@studio.address)

    # スタジオ写真のURLを配列にぶち込む
    if @studio.studio_photos.present?
      @studio.studio_photos.each do |studio_photos|
        @studio_photo_urls.push(studio_photos.photo_url)
      end
    else
      @studio_photo_urls.push("noimage.png")
    end

  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/studios_helper.rb
module StudiosHelper
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="text-center text-muted">© 2018 ソロスタ.</div>
</footer>

app/views/layouts/_imagemap.html.erb
<div>
<img src="/images/imagemap.png" usemap="#ImageMap" alt="" class="img-responsive"/>
<map name="ImageMap">
<!--大田区-->
  <area shape="poly" coords="460,704,404,677,375,676,353,669,339,683,325,676,304,690,282,691,268,677,282,655,275,648,260,648,231,626,203,569,182,569,188,562,182,548,195,540,210,540,211,527,224,513,238,526,238,554,246,541,266,534,296,534,303,548,310,555,339,555,346,562,382,562,389,577,411,577,417,583,432,570,452,583,440,597,396,590,388,598,416,605,403,619,389,612,375,619,382,634,389,627,396,634,418,612,439,606,488,690,461,704,461,704" 
  href="studios?area_id=10" alt="" />
<!--品川区-->
  <area shape="poly" coords="303,448,324,447,338,469,332,476,346,483,353,476,367,483,388,476,389,498,431,561,410,576,389,575,382,561,346,561,339,555,310,554,303,547,296,534,267,533,246,540,239,553,238,526,246,505,260,518,281,483,269,476,289,476,303,468,303,448,325,448,325,448" 
  href="studios?area_id=8" alt="" />
 <!--目黒区-->
  <area shape="poly" coords="225,383,246,383,260,404,288,432,309,433,303,446,303,468,289,475,268,475,281,483,267,504,260,517,246,504,238,525,224,512,210,526,196,505,209,490,196,469,195,455,217,462,231,475,246,440,239,433,246,412,226,384,226,384" 
  href="studios?area_id=9" alt="" />
 <!--世田谷区-->
  <area shape="poly" coords="181,568,173,547,137,519,95,497,59,497,52,490,66,476,55,460,44,441,51,427,58,419,59,405,51,396,51,377,44,362,52,354,51,339,44,333,66,333,87,347,94,362,149,369,184,362,215,362,224,384,245,411,238,432,244,441,230,475,216,461,195,455,194,469,209,489,195,504,209,526,209,540,194,540,181,548,188,562,181,568,181,568" 
  href="studios?area_id=11" alt="" />
 <!--杉並区-->
  <area shape="poly" coords="95,361,87,347,66,332,45,332,59,318,52,311,66,275,51,268,44,253,38,247,44,240,58,246,66,233,109,211,123,219,130,240,137,240,138,247,152,255,159,262,188,269,195,297,203,305,202,318,188,326,188,333,202,347,188,361,152,368,95,361,95,361" 
  href="studios?area_id=12" alt="" />
 <!--練馬区-->
  <area shape="poly" coords="44,254,9,240,2,220,2,217,9,205,9,162,2,141,16,134,44,111,52,98,79,105,66,118,67,119,104,120,123,126,123,90,130,97,130,119,138,120,145,126,203,127,223,147,223,150,216,183,237,184,231,197,237,198,230,218,217,212,203,211,187,233,166,226,166,233,159,233,137,205,130,204,123,219,109,212,66,233,59,247,45,240,38,247,44,253,44,253" 
  href="studios?area_id=14" alt="" />
 <!--中野区-->
  <area shape="poly" coords="202,348,187,333,187,326,202,319,202,305,194,297,188,269,159,262,151,255,137,248,137,241,130,240,123,219,131,204,138,204,159,233,166,233,166,226,187,233,203,211,216,211,230,218,224,240,216,247,230,254,231,262,238,269,258,269,245,283,245,285,251,298,202,347,202,347" 
  href="studios?area_id=13" alt="" />
 <!--港区-->
  <area shape="poly" coords="389,476,368,483,353,476,346,482,332,476,339,468,325,447,303,447,310,433,317,426,317,396,303,396,296,383,304,360,310,347,332,341,346,348,360,362,375,362,396,376,396,383,389,390,389,391,396,405,389,476,388,475,388,475" 
  href="studios?area_id=3" alt="" />
 <!--渋谷区-->
  <area shape="poly" coords="190,361,239,311,268,312,289,326,296,340,310,340,310,347,302,363,296,383,303,397,317,397,317,428,310,434,289,434,260,405,247,385,225,384,217,362,189,362,190,362" 
  href="studios?area_id=4" alt="" />
 <!--新宿区-->
  <area shape="poly" coords="238,311,252,296,245,282,266,261,289,262,295,268,310,254,331,269,359,269,359,289,338,311,331,339,310,347,309,339,295,339,288,325,268,311,238,311,238,311" 
  href="studios?area_id=5" alt="" />
 <!--千代田区-->
  <area shape="poly" coords="396,377,376,363,360,363,347,349,333,341,333,338,339,313,360,292,390,292,404,298,418,285,432,291,432,306,425,327,404,355,397,355,396,377,396,377" 
  href="studios?area_id=1" alt="" />
 <!--中央区-->
  <area shape="poly" coords="433,306,440,319,454,320,460,326,447,347,447,406,419,426,417,426,397,406,390,392,397,384,397,356,404,356,426,327,432,306,432,306" 
  href="studios?area_id=2" alt="" />
 <!--板橋区-->
  <area shape="poly" coords="124,90,125,82,153,68,153,47,260,47,267,54,260,68,281,76,274,97,289,133,310,141,318,177,311,184,297,177,282,204,275,198,261,190,240,197,232,197,239,183,218,183,225,147,204,127,147,127,140,120,132,119,132,98,125,90,125,90" 
  href="studios?area_id=15" alt="" />
 <!--豊島区-->
  <area shape="poly" coords="216,247,223,240,237,197,259,190,274,197,280,204,295,176,309,183,309,189,323,197,330,183,338,183,345,197,352,190,352,190,373,204,366,211,359,204,352,218,345,218,344,232,323,226,316,233,323,246,309,247,309,254,295,268,288,262,265,262,259,269,237,269,230,262,230,254,216,247,216,247" 
  href="studios?area_id=6" alt="" />
 <!--文京区-->
  <area shape="poly" coords="309,254,309,247,323,247,317,233,324,225,345,233,345,218,352,218,359,205,366,211,374,204,402,219,395,240,409,254,416,283,402,297,389,290,359,290,359,269,331,269,310,255,310,255" 
  href="studios?area_id=7" alt="" />
 <!--北区-->
  <area shape="poly" coords="417,218,403,218,374,203,354,189,346,196,339,182,332,182,324,196,310,189,310,182,317,175,310,139,289,132,274,96,282,74,261,67,267,53,288,68,310,68,325,75,346,76,353,96,346,118,367,125,388,118,395,125,388,132,368,146,368,148,374,154,381,154,374,160,374,168,389,175,389,182,396,182,410,189,404,204,417,218,416,217" 
  href="studios?area_id=16" alt="" />
 <!--足立区-->
  <area shape="poly" coords="496,154,510,147,517,153,531,132,553,132,574,118,581,131,588,120,588,118,575,105,560,61,566,54,553,47,525,61,523,61,510,55,510,32,524,25,518,12,497,25,474,26,454,33,431,33,418,12,403,4,389,18,375,12,375,32,396,47,382,68,382,82,353,97,346,118,366,125,388,119,390,120,395,126,389,132,368,146,368,148,374,153,445,162,460,175,460,176,447,183,461,197,496,190,503,203,510,190,517,190,496,155,498,153" 
  href="studios?area_id=17" alt="" />
  <!--荒川区-->
  <area shape="poly" coords="374,161,381,155,446,162,459,175,459,176,446,183,460,197,495,190,502,204,496,225,460,219,452,226,438,226,431,233,424,233,417,219,403,205,410,190,396,183,388,183,388,175,374,168,374,161,374,161" 
  href="studios?area_id=19" alt="" />
 <!--台東区-->
  <area shape="poly" coords="453,317,440,317,432,304,432,289,418,282,411,253,396,239,404,218,418,218,425,232,432,232,439,225,453,225,461,218,496,225,453,296,453,317,453,317" 
  href="studios?area_id=20" alt="" />
 <!--墨田区-->
  <area shape="poly" coords="510,189,518,189,553,246,538,247,538,261,552,269,546,282,530,283,510,276,510,304,496,305,496,326,481,326,474,318,467,326,460,319,453,319,452,298,496,225,503,203,510,191,510,191" 
  href="studios?area_id=21" alt="" />
<!--江東区-->
  <area shape="poly" coords="446,532,404,469,432,447,425,441,453,397,446,348,460,326,454,320,461,320,467,327,475,320,482,327,496,326,496,306,511,305,511,277,530,283,546,284,561,298,568,312,561,413,554,425,553,504,540,504,533,491,525,490,525,461,518,461,511,439,489,440,475,460,475,475,447,532,447,532" 
   href="studios?area_id=22" alt="" />
<!--葛飾区-->
  <area shape="poly" coords="561,60,568,54,582,67,585,67,604,60,618,53,625,60,619,74,632,89,641,82,667,89,661,95,626,118,647,161,633,168,646,182,625,196,604,240,611,261,604,268,576,254,575,268,554,246,497,154,511,147,518,153,533,132,554,132,575,118,582,131,590,117,576,104,562,60,564,59" 
  href="studios?area_id=18" alt="" />
<!--江戸川区-->
  <area shape="poly" coords="633,169,647,162,668,176,675,197,661,225,676,248,704,269,711,290,704,311,682,333,661,333,647,348,646,392,633,426,597,448,576,441,562,414,568,313,561,298,547,284,554,270,539,262,540,248,553,247,575,269,576,256,604,269,611,262,604,241,625,198,647,183,634,170,635,169" 
  href="studios?area_id=23" alt="" />
</map>
</div>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-left" href="/"><img src="/images/logo.png" alt=""></a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/">スタジオを探す</a></li>
      </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_search_area_old.html.erb
  <div class="search well well-lg">
    <div class="row">
      <div class="text-center">
        <%= form_tag(studios_path, method: :get, class: 'form-inline') do %>
          <div class="form-group">
            <%= label_tag :area_id, 'エリア' %>
            <%= select_tag :area_id, 
            options_from_collection_for_select(Area.all, "id", "name", selected: 1)
            %>
          <br><br>
          <%= submit_tag '検索する' ,class: 'btn btn-success btn-lg'%>
          </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/layouts/_searchform.html.erb
<% content_for :cover do %>
  <div class="cover">
    <div class="cover-inner">
      <div class="cover-contents">
        <div class="search well well-lg">
          <div class="row">
            <div class="text-center">
              <%= form_tag(studios_path, method: :get, class: 'form-inline') do %>
                <div class="form-group">
                  <%= label_tag :area_id, 'エリア' %>
                  <%= select_tag :area_id, 
                  options_from_collection_for_select(Area.all, "id", "name", selected: 1)
                  %>
                <br><br>
                <%= submit_tag '検索する' ,class: 'btn btn-success btn-lg'%>
                </div>
              <% end %>
            </div>
          </div>
        </div>
        <!--<a href="" class="btn btn-success btn-lg">さっそく検索する</a>-->
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_sortbutton.html.erb
<!--並び替えボタン&ソート条件配置-->
<table class="noborder_table">
  <tr>
    <td>
      <div class="sort_studios dropdown">
        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
          並び替える
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
        <li class="dropdown-header">平日料金で並び替え</li>
          <li><%=link_to '安い順', studios_path(sort:"charge_weekday",sortby:"平日料金 安い順",area_id:@area_id)%></li>
          <li><%=link_to '高い順', studios_path(sort:"charge_weekday desc",sortby:"平日料金 高い順",area_id:@area_id)%></li>
        <li class="dropdown-header">休日料金で並び替え</li>
          <li><%=link_to '安い順', studios_path(sort:"charge_holiday",sortby:"休日料金 安い順",area_id:@area_id)%></li>
          <li><%=link_to '高い順', studios_path(sort:"charge_holiday desc",sortby:"休日料金 高い順",area_id:@area_id)%></li>
        <li class="dropdown-header">部屋数で並び替え</li>
          <li><%=link_to '少ない順', studios_path(sort:"room",sortby:"部屋数 少ない順",area_id:@area_id)%></li>
          <li><%=link_to '多い順', studios_path(sort:"room desc",sortby:"部屋数 多い順",area_id:@area_id)%></li>
        </ul>
      </div>
    </td>
    <td>
      <div class="sortby">
        <%= @sortby %>
      </div>
    </td>
  </tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 user-scalable=no">
    <script type="text/javascript" src="javascripts/jquery.rwdImageMaps.js"></script>
    <%= favicon_link_tag('/favicon.png') %>

    <title>ソロスタ</title>
    <%= csrf_meta_tags %>

    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- app/assets/stylesheets -->
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">

    <!-- app/assets/javascripts-->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Bootstrap JavaScript-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <%= yield :cover %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>

<script>
$(function(){
  $('img[usemap]').rwdImageMaps();
});
</script>

app/views/studios/index.html.erb
<body>
<div class="contents">
<div class="container">

  <p class="search_header text-center">
    <% if @area.present? %>
      <%= @area.name %>の音楽スタジオ一覧(<%= @hit_count %>件)
    <% else %>
      <h4>都内の音楽スタジオ一覧</h4>
    <% end %>
  </p>
  <div class="search-result well well-lg">
    <div id="sort_box"><%= render 'layouts/sortbutton' %></div>
    <div id="card_box">
        <div class="row row-eq-height">

          <% @studios.each do |studio| %>
          <div class="col-xs-12 col-sm-4 col-lg-4">
            <h2 class="card_header"><span><%=studio.name%></span></h2>
            <div class="card-box">
            <%= link_to studio_path(studio),:style=>"color:black; text-decoration:none;", class: "hoge" do %>
              <div class="card-photo">
                <div class="image_trim">
                  <% if studio.studio_photos.present? %>
                    <img src="/images/studios/<%= studio.studio_photos.first.photo_url %>" alt="<%= studio.name %>" class="img-responsive">
                  <% else %>
                    <img src="/images/studios/noimage.png" alt="noimage" class="img-responsive">
                  <% end %>
                </div>
              </div>
              <div class="card-studio">
                
                        <div class="table-responsive">
                          <table class="table">
                            <tbody>
                                <tr>
                                    <th>エリア</th>
                                    <td><%= @area.name %></td>
                                </tr>
                                <tr>
                                    <th>最寄駅</th>
                                    <td><%= studio.station %></td>
                                </tr>
                                <tr>
                                    <th>営業時間</th>
                                    <td><%= studio.business_hours %></td>
                                </tr>
                                <tr>
                                    <th>定休日</th>
                                    <td><%= studio.day_off %></td>
                                </tr>
                                <tr>
                                    <th>料金(平日)</th>
                                    <td><%= studio.charge_weekday %>円~</td>
                                </tr>
                                <tr>
                                    <th>料金(休日)</th>
                                    <td><%= studio.charge_holiday %>円~</td>
                                </tr>
                                <tr>
                                    <th>部屋数</th>
                                    <td><%= studio.room %></td>
                                </tr>
                            </tbody>
                          </table>
                        </div>                
                
                
                
                
              </div>
            </div>
            <%end%>
          </div>
          <%end%>

        </div>
    </div>
  </div>


</div>
</div>
</body>

app/views/studios/show.html.erb
<h4 class="YuGothic_b"><%= @studio.name %></h4>

<div class="container-show">
<div class="container">
  <div class="row">
<!-- 左側 -->
    <div class="main_left col-xs-12 col-lg-7">

      <div class="image-view">
        <!-- 任意のID指定。クラスとデータ属性の指定。 -->
        <div id="carousel-img" class="carousel slide" data-ride="carousel">
          <!-- インジケーターの設置。下部の○●ボタン。 -->
          <ol class="carousel-indicators">
            <!--枚数に応じて分岐-->
            <% @studio_photo_urls.each_with_index do |studio_photo_url, i| %>
              <% if i == 0 %>
                <li data-target="#carousel-img" data-slide-to="0" class="active"></li>
              <% else %>
                <li data-target="#carousel-img" data-slide-to="1"></li>
              <% end %>
            <% end %>
          </ol>

          <!-- スライドの内容 -->
          <div class="carousel-inner">
            <!--枚数に応じて分岐-->
            <% @studio_photo_urls.each_with_index do |studio_photo_url, i| %>
              <% if i == 0 %>
                <div class="item active">
                  <div class="image_trim">
                  <img src="/images/studios/<%= studio_photo_url %>" alt="">
                  </div>
                </div>
              <% else %>
                <div class="item">
                  <div class="image_trim">
                  <img src="/images/studios/<%= studio_photo_url %>" alt="">
                  </div>
                </div>
              <% end %>
            <% end %>
            
          </div>
          
          <!-- 左右の移動ボタン -->
          <a class="left carousel-control" href="#carousel-img" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
          </a>
          <a class="right carousel-control" href="#carousel-img" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
          </a>
        </div>
      </div>
      <div class="charge">
        <h5><i class="fas fa-info-circle"></i>利用料金</h5>
        <table class="table">
          <thead>
          <tr>
          <th>平日</th>
          <th>土日祝</th>
          </thead>
          <tbody>
          <tr>
          <td><%= @studio.charge_weekday %>円 ~</td>
          <td><%= @studio.charge_holiday %>円 ~</td>
          </tr>
          </tbody>
        </table>
      </div>
      
    </div>
    
<!-- 右側 -->
    <div class="main_right col-xs-12 col-lg-5">
      <div class="studio_info">
        <h5><i class="fas fa-info-circle"></i>基本情報</h5>
        <!-----------最寄駅ここから----------->
        <div class="station row center-block">
          <div class="row">
            <div class="title col-xs-3">
              最寄駅
            </div>
            <div class="content col-xs-9">
              <%= @studio.station %>
            </div>
          </div>
        </div>
        <!-----------最寄駅ここまで----------->
        <!-----------住所ここから----------->
        <div class="address row center-block">
          <div class="row">
            <div class="title col-xs-3">
              住所
            </div>
            <div class="content col-xs-9">
              <%= @studio.address %>
            </div>
          </div>
        </div>
        <!-----------住所ここまで----------->
        <!-----------営業時間ここから----------->
        <div class="business_hours row center-block">
          <div class="row">
            <div class="title col-xs-3">
              営業時間
            </div>
            <div class="content col-xs-9">
              <%= @studio.business_hours %>
            </div>
          </div>
        </div>
        <!-----------営業時間ここまで----------->
        <!-----------定休日ここから----------->
        <div class="day_off row center-block">
          <div class="row">
            <div class="title col-xs-3">
              定休日
            </div>
            <div class="content col-xs-9">
              <%= @studio.day_off %>
            </div>
          </div>
        </div>
        <!-----------定休日ここまで----------->
        <!-----------電話番号ここから----------->
        <div class="tel row center-block">
          <div class="row">
            <div class="title col-xs-3">
              電話番号
            </div>
            <div class="content col-xs-9">
              <%= @studio.tel %>
            </div>
          </div>
        </div>
        <!-----------電話番号ここまで----------->
        <!-----------URLここから----------->
        <div class="url row center-block">
          <div class="row">
            <div class="title col-xs-3">
              URL
            </div>
            <div class="content col-xs-9">
              <%= link_to @studio.url, @studio.url,:target=>["_blank"] %>
            </div>
          </div>
        </div>
        <!-----------URLここまで----------->
      </div>
      
      <div class="map_content">
        <h5><i class="fas fa-map-marker-alt"></i>地図</h5>

          <!--googlemapで開くボタン-->
          <%= link_to  "https://www.google.co.jp/maps?q="+@studio.name+"\s"+@studio.address,
          class: 'googlemap_open btn btn-default btn-xs',:target=>["_blank"] do %>
            <i class="fas fa-external-link-alt"></i>
            <span>GoogleMapで開く</span>
          <% end %>

        <!-- map表示 -->
        <div id="map" class="studio_map"></div>
      </div>
    </div>

  </div>
</div>
</div>























<script type="text/javascript">
function initMap() {

  var test ={lat: <%= @place["lat"] %>, lng: <%= @place["lng"] %>};
  var map = new google.maps.Map(document.getElementById('map'), {
    zoom: 15,
    center: test
  });
  var transitLayer = new google.maps.TransitLayer();
  transitLayer.setMap(map);

  var contentString = '住所：<%= @studio.address %>';
  var infowindow = new google.maps.InfoWindow({
    content: contentString
  });

  var marker = new google.maps.Marker({
    position:test,
    map: map,
    title: contentString
  });

  marker.addListener('click', function() {
    infowindow.open(map, marker);
  });
}
 </script>
 
 <script async defer
   src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=AIzaSyBfR6RF3Bxj1C9Qa9-JzyxqXejrQL6kZas&callback=initMap">
 </script>
 

app/views/toppages/index.html.erb
<body>
<div class="contents">

<div class="container">

  <p class="search_header text-center">エリアを指定してスタジオを探そう！</p>
  <div class="search well well-lg">
    <div class="row">
      
      <div class="image_map text-center col-xs-12 col-sm-8 col-lg-7 col-lg-offset-1">
          <%= render 'layouts/imagemap' %>
      </div>
      
      <div class="area_ranking col-xs-12 col-sm-4 col-lg-4">
        <h6>スタジオが多いエリア</h6>
        <ol class="ol_custum">
          <%count_ranking = 5%>
          <%i = 0%>
          <%for areas in Area.ranking_method do%>
            <%if i<count_ranking then%>
            <li>
              <a href="studios?area_id=<%=Area.find_by(name: areas[0]).id%>"><h5><%=areas[0]%><span class="how_many_studios">【<%=areas[1]%>件】</span></h5></a>
            </li>
            <%end%>
            <%i=i+1 %>
          <%end%>
        </ol>
      </div>
      
    </div>
  </div>
</div>

</div>
</body>